name: 'github_analytics'
version: '1.0.0'

profile: 'github_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  github_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      silver:
        +materialized: table
        issues_current:
          +materialized: view
        pull_requests_current:
          +materialized: view
        repositories_current:
          +materialized: view
      gold:
        +schema: gold
        +materialized: table

snapshots:
  github_analytics:
    +target_schema: silver_snapshots
